- updated for 2.4.6
Changed files:
    abiword-goffice03.patch -> 1.4

diff --git a/abiword-goffice03.patch b/abiword-goffice03.patch
--- a/abiword-goffice03.patch
+++ b/abiword-goffice03.patch
@@ -1,18 +1,16 @@
-diff -aurN abiword-plugins.orig/tools/abigochart/plugin.m4 abiword-plugins/tools/abigochart/plugin.m4
---- abiword-plugins.orig/tools/abigochart/plugin.m4	2005-12-27 12:09:54.000000000 +0100
-+++ abiword-plugins/tools/abigochart/plugin.m4	2006-06-11 19:18:51.900687200 +0200
+--- abiword-plugins/tools/abigochart/plugin.m4~	2006-10-31 22:25:11.000000000 +0100
++++ abiword-plugins/tools/abigochart/plugin.m4	2006-11-17 13:33:03.318315000 +0100
 @@ -23,7 +23,7 @@
  
- LIBGOffice_REQUIRED_VERSION=0.1.0
+ LIBGOffice_REQUIRED_VERSION=0.2.1
  
 -PKG_CHECK_MODULES(GOFFICE, [libgoffice-1 >= $LIBGOffice_REQUIRED_VERSION],[
 +PKG_CHECK_MODULES(GOFFICE, [libgoffice-0.3 >= $LIBGOffice_REQUIRED_VERSION],[
          ABI_PLUGIN_REPORT([abigochart: okay])
  ],[        ABI_PLUGIN_REPORT([abigochart: error libgoffice >= $LIBGOffice_REQUIRED_VERSION required])
          abi_plugin_disable=yes
-diff -aurN abiword-plugins.orig/tools/abigochart/unix/AbiGOChart.cpp abiword-plugins/tools/abigochart/unix/AbiGOChart.cpp
---- abiword-plugins.orig/tools/abigochart/unix/AbiGOChart.cpp	2006-03-26 15:28:54.000000000 +0200
-+++ abiword-plugins/tools/abigochart/unix/AbiGOChart.cpp	2006-10-26 22:36:49.179956728 +0200
+--- abiword-plugins/tools/abigochart/unix/AbiGOChart.cpp~	2006-10-31 22:25:12.000000000 +0100
++++ abiword-plugins/tools/abigochart/unix/AbiGOChart.cpp	2006-11-17 13:35:44.258315000 +0100
 @@ -72,7 +72,7 @@
  #include <goffice/graph/gog-data-allocator.h>
  #include <goffice/graph/gog-series.h>
@@ -22,19 +20,19 @@ diff -aurN abiword-plugins.orig/tools/abigochart/unix/AbiGOChart.cpp abiword-plu
  #include <goffice/graph/gog-data-set.h>
  #include <goffice/graph/gog-object-xml.h>
  #include <goffice/data/go-data-simple.h>
-@@ -1102,7 +1102,7 @@
+@@ -1119,7 +1119,7 @@
  {
  	m_Graph = NULL;
  	m_Image = NULL;
 -	m_Renderer = GOG_RENDERER (g_object_new (GOG_RENDERER_PIXBUF_TYPE, NULL));
 +	m_Renderer = GOG_RENDERER (g_object_new (GOG_RENDERER_CAIRO_TYPE, NULL));
+ 	pix_width = pix_height = 0;
  	width = height = 0;
  	m_Guru = NULL;
- }
-@@ -1157,10 +1157,10 @@
+@@ -1189,10 +1189,10 @@
  			GdkPixbuf *pixbuf;
- 			width = _width;
- 			height = _height;
+ 			pix_width = _width;
+ 			pix_height = _height;
 -			gog_renderer_pixbuf_update (GOG_RENDERER_PIXBUF (m_Renderer), _width, _height, 1.0);	
 +			gog_renderer_cairo_update (GOG_RENDERER_CAIRO (m_Renderer), _width, _height, 1.0);	
  			if (m_Image)
@@ -44,12 +42,49 @@ diff -aurN abiword-plugins.orig/tools/abigochart/unix/AbiGOChart.cpp abiword-plu
  			m_Image = new GR_UnixImage(NULL, pixbuf);
  			g_object_ref(pixbuf);
  			m_Image->scaleImageTo(m_pGOMan->getGraphics(),rec);
-@@ -1256,7 +1256,7 @@
- 	/* the resolution of symbols in libgoffice must be forced because when
- 	creating the guru window, libglade needs foo_canvas_new. There might
- 	be a better solution..., I could not find one */
--	g_module_close (g_module_open ("libgoffice-1", (GModuleFlags)0));
-+	g_module_close (g_module_open ("libgoffice-0.3", (GModuleFlags)0));
-    return 1;
- }
- 
+--- abiword-plugins/configure~	2006-11-17 13:08:32.000000000 +0100
++++ abiword-plugins/configure	2006-11-17 13:51:20.348315000 +0100
+@@ -24074,12 +24074,12 @@
+         pkg_cv_GOFFICE_CFLAGS="$GOFFICE_CFLAGS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libgoffice-1 >= \$LIBGOffice_REQUIRED_VERSION\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "libgoffice-1 >= $LIBGOffice_REQUIRED_VERSION") 2>&5
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libgoffice-0.3 >= \$LIBGOffice_REQUIRED_VERSION\"") >&5
++  ($PKG_CONFIG --exists --print-errors "libgoffice-0.3 >= $LIBGOffice_REQUIRED_VERSION") 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_GOFFICE_CFLAGS=`$PKG_CONFIG --cflags "libgoffice-1 >= $LIBGOffice_REQUIRED_VERSION" 2>/dev/null`
++  pkg_cv_GOFFICE_CFLAGS=`$PKG_CONFIG --cflags "libgoffice-0.3 >= $LIBGOffice_REQUIRED_VERSION" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -24092,12 +24092,12 @@
+         pkg_cv_GOFFICE_LIBS="$GOFFICE_LIBS"
+     else
+         if test -n "$PKG_CONFIG" && \
+-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libgoffice-1 >= \$LIBGOffice_REQUIRED_VERSION\"") >&5
+-  ($PKG_CONFIG --exists --print-errors "libgoffice-1 >= $LIBGOffice_REQUIRED_VERSION") 2>&5
++    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libgoffice-0.3 >= \$LIBGOffice_REQUIRED_VERSION\"") >&5
++  ($PKG_CONFIG --exists --print-errors "libgoffice-0.3 >= $LIBGOffice_REQUIRED_VERSION") 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }; then
+-  pkg_cv_GOFFICE_LIBS=`$PKG_CONFIG --libs "libgoffice-1 >= $LIBGOffice_REQUIRED_VERSION" 2>/dev/null`
++  pkg_cv_GOFFICE_LIBS=`$PKG_CONFIG --libs "libgoffice-0.3 >= $LIBGOffice_REQUIRED_VERSION" 2>/dev/null`
+ else
+   pkg_failed=yes
+ fi
+@@ -24116,9 +24116,9 @@
+         _pkg_short_errors_supported=no
+ fi
+         if test $_pkg_short_errors_supported = yes; then
+-	        GOFFICE_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "libgoffice-1 >= $LIBGOffice_REQUIRED_VERSION"`
++	        GOFFICE_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "libgoffice-0.3 >= $LIBGOffice_REQUIRED_VERSION"`
+         else
+-	        GOFFICE_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libgoffice-1 >= $LIBGOffice_REQUIRED_VERSION"`
++	        GOFFICE_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libgoffice-0.3 >= $LIBGOffice_REQUIRED_VERSION"`
+         fi
+ 	# Put the nasty error message in config.log where it belongs
+ 	echo "$GOFFICE_PKG_ERRORS" >&5
